services:
  db:
    image: postgres:16
    container_name: my_project_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

# This top-level key defines the named volume we used above.
# Docker manages this volume, ensuring your data is safe.
volumes:
  postgres_data:
    driver: local
